In [1]:
"""
使用torch实现二分类的功能Step1：仅将numpy改为torch，并优化损失函数、添加重构
"""
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
# 训练集和验证集，四组数据，三维向量
x_train, y_train, x_valid, y_valid = [[1.0,2,3], [2,3,4], [3,4,5], [4,5,6]], [0, 0, 1, 1], [[7.0,9,8], [0,0,0]], [1, 0]
# 改变格式
x_train, y_train, x_valid, y_valid = map(
    torch.tensor, (x_train, y_train, x_valid, y_valid)  )
# 重构
class Mnist_Logistic(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.ones((3,2)))
        self.bias = nn.Parameter(torch.zeros(2))

    def forward(self, xb):
        return xb @ self.weights + self.bias

In [3]:
# 实例化模型
model = Mnist_Logistic()
# 损失函数，交叉熵
loss_func = F.cross_entropy
# 准确率
def accuracy(out, yb):
    preds = torch.argmax(out, dim=1)
    return (preds == yb).float().mean()
# 观察结果
# bs = 2  # batch size
# xb = x_train[0:bs]  # a mini-batch from x
# yb = y_train[0:bs]
# print(loss_func(model(xb), yb), accuracy(model(xb), yb))

In [4]:
# 多次迭代
lr = 0.5  # learning rate
epochs = 2  # how many epochs to train for
bs = 2  # batch size
for epoch in range(epochs):
    for i in range((x_train.shape[0] - 1) // bs + 1):
        start_i = i * bs
        end_i = start_i + bs
        xb = x_train[start_i:end_i]
        yb = y_train[start_i:end_i]
        pred = model(xb)
        loss = loss_func(pred, yb)

        print('epoch=', epoch, 'batchnum=', i, 'loss=', loss, '\nweights=\n', model.weights)

        loss.backward()
        with torch.no_grad():
            for p in model.parameters():
                p -= p.grad * lr
            model.zero_grad()

print('loss=', loss_func(model(x_train), y_train), 'accuracy=', accuracy(model(x_valid), y_valid), '\nweights=\n', model.weights, '\nbias=', model.bias)


epoch= 0 batchnum= 0 loss= tensor(0.6931, grad_fn=<NllLossBackward>) 
weights=
 Parameter containing:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
epoch= 0 batchnum= 1 loss= tensor(18.3750, grad_fn=<NllLossBackward>) 
weights=
 Parameter containing:
tensor([[1.3750, 0.6250],
        [1.6250, 0.3750],
        [1.8750, 0.1250]], requires_grad=True)
epoch= 1 batchnum= 0 loss= tensor(25.8750, grad_fn=<NllLossBackward>) 
weights=
 Parameter containing:
tensor([[-0.3750,  2.3750],
        [-0.6250,  2.6250],
        [-0.8750,  2.8750]], requires_grad=True)
epoch= 1 batchnum= 1 loss= tensor(0.0003, grad_fn=<NllLossBackward>) 
weights=
 Parameter containing:
tensor([[0.3750, 1.6250],
        [0.6250, 1.3750],
        [0.8750, 1.1250]], requires_grad=True)
loss= tensor(2.0811, grad_fn=<NllLossBackward>) accuracy= tensor(1.) 
weights=
 Parameter containing:
tensor([[0.3745, 1.6255],
        [0.6244, 1.3756],
        [0.8742, 1.1258]], requires_grad=True) 
bias= Para

/home/t-wanjunwang/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(
